### ISSUE TITLE
Archive CSV-JSON

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris/interlok-csv-json#138]
Update the README and archive csv-json since it is now part of the interlok-csv project as a sub-module

Since https://github.com/adaptris/interlok-csv/pull/175 is merged we no longer need the top level interlok-csv-json project.

- interlok-csv-json proper should be archived.
- interlok-csv-json should be removed from internal CI pipeline
- interlok-csv-json should be removed release scripts (since it will be part of interlok-csv)

Yes, I know that this is a duplicate of https://github.com/adaptris/interlok-csv/issues/176

**Comment by sebastien-belin-adp** [comment]
interlok-csv-json is now archived
